autoscrape:
    # The type of runner that the job will run on
    runs-on: macOS-11
    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master
    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("rmarkdown")'
        R -e 'install.packages("gtrendsR")'
        R -e 'install.packages("magrittr")'
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("xts")'
        R -e 'install.packages("tbl2xts")'
        R -e 'install.packages("dygraphs")'
        R -e 'install.packages("rgdal")'
        R -e 'install.packages("RColorBrewer")'
        R -e 'install.packages("leaflet")'
        R -e 'install.packages("wordcloud")'
        R -e 'install.packages("flexdashboard")'
    
    # Run R script
    - name: Covid_Trends
      run: Rscript covid_trends.Rmd

 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/*
        git commit -am "GH ACTION Headlines $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
username: github-actions
